export const REQUST_FETCH_JOBLIST='REQUST_FETCH_JOBLIST'
export const FETCH_JOBLIST_SUCCESS='FETCH_JOBLIST_SUCCESS'
export const FETCH_JOB_CONTENT='FETCH_JOB_CONTENT'

export const FETCH_JOBLIST_Failed='FETCH_JOBLIST_Failed'
